### ISSUE TITLE
How to link ipv6 network ? 

### ISSUE THREAD

**Issue by cvbni** [esp-rs/esp-idf-svc#363]
https://github.com/esp-rs/esp-idf-svc/blob/master/examples/mqtt_client_async.rs
This example can link to ipv4 MQTT URL, but can't link to ipv6 MQTT URL

Thanks !

**Comment by ivmarkov** [comment]
Well, I think in the meantime I at least have _some_ idea how that could work:

To talk ipv6 to services sitting on the internet (or in general outside of your link-local network) you have to do three things:
(a) Make sure that your ISP actually does assign you an ipv6 segment in the first place
(b) Make sure that your router actually does "speak" ipv6 and therefore the computers in your local LAN can use the ipv6 segment assigned to you by your ISP
(c) Enable [`CONFIG_LWIP_IPV6_AUTOCONFIG`](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/kconfig.html#config-lwip-ipv6-autoconfig) in your `sdkconfig.defaults`. Not sure if you need to call an API after that, or the SLAAC public IPv6 assignment on your Wifi happens "automagically", you need to check that.
(c) Possibly also call `dhcp6_enable_stateless(netif);` where `netif` is your `wifi.sta_netif()`, if you 1- do have dhcpv6 on your router 2- you want dns64 resolution with dns64 servers given to the ESP by the router. Note that - as per the ESP IDF documentation - ESP IDF does not really support what is called the "stateful" DHCPv6 (i.e. assigning an ipv6 address to the Esp which is picked up by the router; ESP-IDF uses SLAAC for this), but ESP IDF _does_ support the statelsss aspect od dhcpv6 which is nothing else but a way for the Esp to get a list of dns64 dns servers that the router knows about, so that the name resolution of ipv6 servers on the internet works for the esp without any explicit dns64 configuration.

All of the above of course assumes that the C mqtt ESP IDF component does speak ipv6, which I haven't checked. But I doubt it doesn't.
